### PR TITLE
Fix markdown example for build badge.

### PR DESCRIPTION
**Pull request by angularsen**
Image url should be specified first, link url second. The original example did not work on Github at least.

### CODE REVIEW

**Comment by jfromaniello** [comment]
thank you!

**Comment by jfromaniello** [comment]
BTW, yersterday github did something and now it cache images over http and https. I'm not sure if this project will still work, i think i should respond request with some cache headers

**Comment by angularsen** [comment]
Oh, HTTPS is cached as well now? A quick google don't reveal any good solutions to this except HTTPS. Not sure if their CDN respects the cache headers you output, but it's worth a try.

**Comment by jfromaniello** [comment]
Yes, it seems that nocache is the only way:

https://twitter.com/holman/status/428437815018278912

**Comment by angularsen** [comment]
You might be interested to know that TeamCity's built in solution also seem to use no-cache header.

**Pull request merged**
